# Generated by Django 3.1.7 on 2021-06-01 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
